"""NeetCode 250 delta catalog (catalog-only seed).

The NeetCode 250 is the NeetCode 150 plus ~100 extra problems. Entries
already covered by the authored sources or the 150 catalog are omitted
here (deduplicated by LeetCode slug in app/seeds/__init__.py).

Generated from the NeetCode 250 list (250 entries) — only the delta is
stored. Each entry carries title / slug / difficulty / topic / category /
pattern_key plus sources=["neetcode"]. They seed as catalog placeholders
(unsolvable until authored) and appear on the roadmap under their pattern.
"""

NEETCODE_250: list[dict] = [
    {
        'title': 'Concatenation of Array',
        'slug': 'concatenation-of-array',
        'difficulty': 'EASY',
        'topic': 'ARRAY',
        'category': 'Arrays & Hashing',
        'pattern_key': 'arrays-hashing',
        'sources': ['neetcode'],
    },
    {
        'title': 'Longest Common Prefix',
        'slug': 'longest-common-prefix',
        'difficulty': 'EASY',
        'topic': 'ARRAY',
        'category': 'Arrays & Hashing',
        'pattern_key': 'arrays-hashing',
        'sources': ['neetcode'],
    },
    {
        'title': 'Remove Element',
        'slug': 'remove-element',
        'difficulty': 'EASY',
        'topic': 'ARRAY',
        'category': 'Arrays & Hashing',
        'pattern_key': 'arrays-hashing',
        'sources': ['neetcode'],
    },
    {
        'title': 'Majority Element',
        'slug': 'majority-element',
        'difficulty': 'EASY',
        'topic': 'ARRAY',
        'category': 'Arrays & Hashing',
        'pattern_key': 'arrays-hashing',
        'sources': ['neetcode'],
    },
    {
        'title': 'Design HashSet',
        'slug': 'design-hashset',
        'difficulty': 'EASY',
        'topic': 'ARRAY',
        'category': 'Arrays & Hashing',
        'pattern_key': 'arrays-hashing',
        'sources': ['neetcode'],
    },
    {
        'title': 'Design HashMap',
        'slug': 'design-hashmap',
        'difficulty': 'EASY',
        'topic': 'ARRAY',
        'category': 'Arrays & Hashing',
        'pattern_key': 'arrays-hashing',
        'sources': ['neetcode'],
    },
    {
        'title': 'Sort an Array',
        'slug': 'sort-an-array',
        'difficulty': 'MEDIUM',
        'topic': 'ARRAY',
        'category': 'Arrays & Hashing',
        'pattern_key': 'arrays-hashing',
        'sources': ['neetcode'],
    },
    {
        'title': 'Sort Colors',
        'slug': 'sort-colors',
        'difficulty': 'MEDIUM',
        'topic': 'ARRAY',
        'category': 'Arrays & Hashing',
        'pattern_key': 'arrays-hashing',
        'sources': ['neetcode'],
    },
    {
        'title': 'Range Sum Query 2D Immutable',
        'slug': 'range-sum-query-2d-immutable',
        'difficulty': 'MEDIUM',
        'topic': 'ARRAY',
        'category': 'Arrays & Hashing',
        'pattern_key': 'arrays-hashing',
        'sources': ['neetcode'],
    },
    {
        'title': 'Best Time to Buy And Sell Stock II',
        'slug': 'best-time-to-buy-and-sell-stock-ii',
        'difficulty': 'MEDIUM',
        'topic': 'ARRAY',
        'category': 'Arrays & Hashing',
        'pattern_key': 'arrays-hashing',
        'sources': ['neetcode'],
    },
    {
        'title': 'Majority Element II',
        'slug': 'majority-element-ii',
        'difficulty': 'MEDIUM',
        'topic': 'ARRAY',
        'category': 'Arrays & Hashing',
        'pattern_key': 'arrays-hashing',
        'sources': ['neetcode'],
    },
    {
        'title': 'Reverse String',
        'slug': 'reverse-string',
        'difficulty': 'EASY',
        'topic': 'ARRAY',
        'category': 'Two Pointers',
        'pattern_key': 'two-pointers',
        'sources': ['neetcode'],
    },
    {
        'title': 'Valid Palindrome II',
        'slug': 'valid-palindrome-ii',
        'difficulty': 'EASY',
        'topic': 'ARRAY',
        'category': 'Two Pointers',
        'pattern_key': 'two-pointers',
        'sources': ['neetcode'],
    },
    {
        'title': 'Merge Strings Alternately',
        'slug': 'merge-strings-alternately',
        'difficulty': 'EASY',
        'topic': 'ARRAY',
        'category': 'Two Pointers',
        'pattern_key': 'two-pointers',
        'sources': ['neetcode'],
    },
    {
        'title': 'Merge Sorted Array',
        'slug': 'merge-sorted-array',
        'difficulty': 'EASY',
        'topic': 'ARRAY',
        'category': 'Two Pointers',
        'pattern_key': 'two-pointers',
        'sources': ['neetcode'],
    },
    {
        'title': 'Remove Duplicates From Sorted Array',
        'slug': 'remove-duplicates-from-sorted-array',
        'difficulty': 'EASY',
        'topic': 'ARRAY',
        'category': 'Two Pointers',
        'pattern_key': 'two-pointers',
        'sources': ['neetcode'],
    },
    {
        'title': '4Sum',
        'slug': '4sum',
        'difficulty': 'MEDIUM',
        'topic': 'ARRAY',
        'category': 'Two Pointers',
        'pattern_key': 'two-pointers',
        'sources': ['neetcode'],
    },
    {
        'title': 'Rotate Array',
        'slug': 'rotate-array',
        'difficulty': 'MEDIUM',
        'topic': 'ARRAY',
        'category': 'Two Pointers',
        'pattern_key': 'two-pointers',
        'sources': ['neetcode'],
    },
    {
        'title': 'Boats to Save People',
        'slug': 'boats-to-save-people',
        'difficulty': 'MEDIUM',
        'topic': 'ARRAY',
        'category': 'Two Pointers',
        'pattern_key': 'two-pointers',
        'sources': ['neetcode'],
    },
    {
        'title': 'Contains Duplicate II',
        'slug': 'contains-duplicate-ii',
        'difficulty': 'EASY',
        'topic': 'STRING',
        'category': 'Sliding Window',
        'pattern_key': 'sliding-window',
        'sources': ['neetcode'],
    },
    {
        'title': 'Minimum Size Subarray Sum',
        'slug': 'minimum-size-subarray-sum',
        'difficulty': 'MEDIUM',
        'topic': 'STRING',
        'category': 'Sliding Window',
        'pattern_key': 'sliding-window',
        'sources': ['neetcode'],
    },
    {
        'title': 'Find K Closest Elements',
        'slug': 'find-k-closest-elements',
        'difficulty': 'MEDIUM',
        'topic': 'STRING',
        'category': 'Sliding Window',
        'pattern_key': 'sliding-window',
        'sources': ['neetcode'],
    },
    {
        'title': 'Baseball Game',
        'slug': 'baseball-game',
        'difficulty': 'EASY',
        'topic': 'STACK',
        'category': 'Stack',
        'pattern_key': 'stack',
        'sources': ['neetcode'],
    },
    {
        'title': 'Implement Stack Using Queues',
        'slug': 'implement-stack-using-queues',
        'difficulty': 'EASY',
        'topic': 'STACK',
        'category': 'Stack',
        'pattern_key': 'stack',
        'sources': ['neetcode'],
    },
    {
        'title': 'Implement Queue using Stacks',
        'slug': 'implement-queue-using-stacks',
        'difficulty': 'EASY',
        'topic': 'STACK',
        'category': 'Stack',
        'pattern_key': 'stack',
        'sources': ['neetcode'],
    },
    {
        'title': 'Asteroid Collision',
        'slug': 'asteroid-collision',
        'difficulty': 'MEDIUM',
        'topic': 'STACK',
        'category': 'Stack',
        'pattern_key': 'stack',
        'sources': ['neetcode'],
    },
    {
        'title': 'Online Stock Span',
        'slug': 'online-stock-span',
        'difficulty': 'MEDIUM',
        'topic': 'STACK',
        'category': 'Stack',
        'pattern_key': 'stack',
        'sources': ['neetcode'],
    },
    {
        'title': 'Simplify Path',
        'slug': 'simplify-path',
        'difficulty': 'MEDIUM',
        'topic': 'STACK',
        'category': 'Stack',
        'pattern_key': 'stack',
        'sources': ['neetcode'],
    },
    {
        'title': 'Decode String',
        'slug': 'decode-string',
        'difficulty': 'MEDIUM',
        'topic': 'STACK',
        'category': 'Stack',
        'pattern_key': 'stack',
        'sources': ['neetcode'],
    },
    {
        'title': 'Maximum Frequency Stack',
        'slug': 'maximum-frequency-stack',
        'difficulty': 'HARD',
        'topic': 'STACK',
        'category': 'Stack',
        'pattern_key': 'stack',
        'sources': ['neetcode'],
    },
    {
        'title': 'Search Insert Position',
        'slug': 'search-insert-position',
        'difficulty': 'EASY',
        'topic': 'ARRAY',
        'category': 'Binary Search',
        'pattern_key': 'binary-search',
        'sources': ['neetcode'],
    },
    {
        'title': 'Guess Number Higher Or Lower',
        'slug': 'guess-number-higher-or-lower',
        'difficulty': 'EASY',
        'topic': 'ARRAY',
        'category': 'Binary Search',
        'pattern_key': 'binary-search',
        'sources': ['neetcode'],
    },
    {
        'title': 'Sqrt(x)',
        'slug': 'sqrtx',
        'difficulty': 'EASY',
        'topic': 'ARRAY',
        'category': 'Binary Search',
        'pattern_key': 'binary-search',
        'sources': ['neetcode'],
    },
    {
        'title': 'Capacity to Ship Packages Within D Days',
        'slug': 'capacity-to-ship-packages-within-d-days',
        'difficulty': 'MEDIUM',
        'topic': 'ARRAY',
        'category': 'Binary Search',
        'pattern_key': 'binary-search',
        'sources': ['neetcode'],
    },
    {
        'title': 'Search In Rotated Sorted Array II',
        'slug': 'search-in-rotated-sorted-array-ii',
        'difficulty': 'MEDIUM',
        'topic': 'ARRAY',
        'category': 'Binary Search',
        'pattern_key': 'binary-search',
        'sources': ['neetcode'],
    },
    {
        'title': 'Split Array Largest Sum',
        'slug': 'split-array-largest-sum',
        'difficulty': 'HARD',
        'topic': 'ARRAY',
        'category': 'Binary Search',
        'pattern_key': 'binary-search',
        'sources': ['neetcode'],
    },
    {
        'title': 'Find in Mountain Array',
        'slug': 'find-in-mountain-array',
        'difficulty': 'HARD',
        'topic': 'ARRAY',
        'category': 'Binary Search',
        'pattern_key': 'binary-search',
        'sources': ['neetcode'],
    },
    {
        'title': 'Reverse Linked List II',
        'slug': 'reverse-linked-list-ii',
        'difficulty': 'MEDIUM',
        'topic': 'LINKED_LIST',
        'category': 'Linked List',
        'pattern_key': 'linked-list',
        'sources': ['neetcode'],
    },
    {
        'title': 'Design Circular Queue',
        'slug': 'design-circular-queue',
        'difficulty': 'MEDIUM',
        'topic': 'LINKED_LIST',
        'category': 'Linked List',
        'pattern_key': 'linked-list',
        'sources': ['neetcode'],
    },
    {
        'title': 'LFU Cache',
        'slug': 'lfu-cache',
        'difficulty': 'HARD',
        'topic': 'LINKED_LIST',
        'category': 'Linked List',
        'pattern_key': 'linked-list',
        'sources': ['neetcode'],
    },
    {
        'title': 'Binary Tree Inorder Traversal',
        'slug': 'binary-tree-inorder-traversal',
        'difficulty': 'EASY',
        'topic': 'TREE',
        'category': 'Trees',
        'pattern_key': 'trees',
        'sources': ['neetcode'],
    },
    {
        'title': 'Binary Tree Preorder Traversal',
        'slug': 'binary-tree-preorder-traversal',
        'difficulty': 'EASY',
        'topic': 'TREE',
        'category': 'Trees',
        'pattern_key': 'trees',
        'sources': ['neetcode'],
    },
    {
        'title': 'Binary Tree Postorder Traversal',
        'slug': 'binary-tree-postorder-traversal',
        'difficulty': 'EASY',
        'topic': 'TREE',
        'category': 'Trees',
        'pattern_key': 'trees',
        'sources': ['neetcode'],
    },
    {
        'title': 'Maximum Depth of Binary Tree',
        'slug': 'maximum-depth-of-binary-tree',
        'difficulty': 'EASY',
        'topic': 'TREE',
        'category': 'Trees',
        'pattern_key': 'trees',
        'sources': ['neetcode'],
    },
    {
        'title': 'Lowest Common Ancestor of a Binary Search Tree',
        'slug': 'lowest-common-ancestor-of-a-binary-search-tree',
        'difficulty': 'MEDIUM',
        'topic': 'TREE',
        'category': 'Trees',
        'pattern_key': 'trees',
        'sources': ['neetcode'],
    },
    {
        'title': 'Insert into a Binary Search Tree',
        'slug': 'insert-into-a-binary-search-tree',
        'difficulty': 'MEDIUM',
        'topic': 'TREE',
        'category': 'Trees',
        'pattern_key': 'trees',
        'sources': ['neetcode'],
    },
    {
        'title': 'Delete Node in a BST',
        'slug': 'delete-node-in-a-bst',
        'difficulty': 'MEDIUM',
        'topic': 'TREE',
        'category': 'Trees',
        'pattern_key': 'trees',
        'sources': ['neetcode'],
    },
    {
        'title': 'Construct Quad Tree',
        'slug': 'construct-quad-tree',
        'difficulty': 'MEDIUM',
        'topic': 'TREE',
        'category': 'Trees',
        'pattern_key': 'trees',
        'sources': ['neetcode'],
    },
    {
        'title': 'House Robber III',
        'slug': 'house-robber-iii',
        'difficulty': 'MEDIUM',
        'topic': 'TREE',
        'category': 'Trees',
        'pattern_key': 'trees',
        'sources': ['neetcode'],
    },
    {
        'title': 'Delete Leaves With a Given Value',
        'slug': 'delete-leaves-with-a-given-value',
        'difficulty': 'MEDIUM',
        'topic': 'TREE',
        'category': 'Trees',
        'pattern_key': 'trees',
        'sources': ['neetcode'],
    },
    {
        'title': 'Single Threaded CPU',
        'slug': 'single-threaded-cpu',
        'difficulty': 'MEDIUM',
        'topic': 'QUEUE',
        'category': 'Heap / Priority Queue',
        'pattern_key': 'heap-priority-queue',
        'sources': ['neetcode'],
    },
    {
        'title': 'Reorganize String',
        'slug': 'reorganize-string',
        'difficulty': 'MEDIUM',
        'topic': 'QUEUE',
        'category': 'Heap / Priority Queue',
        'pattern_key': 'heap-priority-queue',
        'sources': ['neetcode'],
    },
    {
        'title': 'Longest Happy String',
        'slug': 'longest-happy-string',
        'difficulty': 'MEDIUM',
        'topic': 'QUEUE',
        'category': 'Heap / Priority Queue',
        'pattern_key': 'heap-priority-queue',
        'sources': ['neetcode'],
    },
    {
        'title': 'Car Pooling',
        'slug': 'car-pooling',
        'difficulty': 'MEDIUM',
        'topic': 'QUEUE',
        'category': 'Heap / Priority Queue',
        'pattern_key': 'heap-priority-queue',
        'sources': ['neetcode'],
    },
    {
        'title': 'IPO',
        'slug': 'ipo',
        'difficulty': 'HARD',
        'topic': 'QUEUE',
        'category': 'Heap / Priority Queue',
        'pattern_key': 'heap-priority-queue',
        'sources': ['neetcode'],
    },
    {
        'title': 'Sum of All Subsets XOR Total',
        'slug': 'sum-of-all-subset-xor-totals',
        'difficulty': 'EASY',
        'topic': 'ARRAY',
        'category': 'Backtracking',
        'pattern_key': 'backtracking',
        'sources': ['neetcode'],
    },
    {
        'title': 'Combinations',
        'slug': 'combinations',
        'difficulty': 'MEDIUM',
        'topic': 'ARRAY',
        'category': 'Backtracking',
        'pattern_key': 'backtracking',
        'sources': ['neetcode'],
    },
    {
        'title': 'Permutations II',
        'slug': 'permutations-ii',
        'difficulty': 'MEDIUM',
        'topic': 'ARRAY',
        'category': 'Backtracking',
        'pattern_key': 'backtracking',
        'sources': ['neetcode'],
    },
    {
        'title': 'Matchsticks to Square',
        'slug': 'matchsticks-to-square',
        'difficulty': 'MEDIUM',
        'topic': 'ARRAY',
        'category': 'Backtracking',
        'pattern_key': 'backtracking',
        'sources': ['neetcode'],
    },
    {
        'title': 'Partition to K Equal Sum Subsets',
        'slug': 'partition-to-k-equal-sum-subsets',
        'difficulty': 'MEDIUM',
        'topic': 'ARRAY',
        'category': 'Backtracking',
        'pattern_key': 'backtracking',
        'sources': ['neetcode'],
    },
    {
        'title': 'N Queens II',
        'slug': 'n-queens-ii',
        'difficulty': 'HARD',
        'topic': 'ARRAY',
        'category': 'Backtracking',
        'pattern_key': 'backtracking',
        'sources': ['neetcode'],
    },
    {
        'title': 'Word Break II',
        'slug': 'word-break-ii',
        'difficulty': 'HARD',
        'topic': 'ARRAY',
        'category': 'Backtracking',
        'pattern_key': 'backtracking',
        'sources': ['neetcode'],
    },
    {
        'title': 'Extra Characters in a String',
        'slug': 'extra-characters-in-a-string',
        'difficulty': 'MEDIUM',
        'topic': 'TREE',
        'category': 'Tries',
        'pattern_key': 'tries',
        'sources': ['neetcode'],
    },
    {
        'title': 'Island Perimeter',
        'slug': 'island-perimeter',
        'difficulty': 'EASY',
        'topic': 'GRAPH',
        'category': 'Graphs',
        'pattern_key': 'graphs',
        'sources': ['neetcode'],
    },
    {
        'title': 'Verifying An Alien Dictionary',
        'slug': 'verifying-an-alien-dictionary',
        'difficulty': 'EASY',
        'topic': 'GRAPH',
        'category': 'Graphs',
        'pattern_key': 'graphs',
        'sources': ['neetcode'],
    },
    {
        'title': 'Find the Town Judge',
        'slug': 'find-the-town-judge',
        'difficulty': 'EASY',
        'topic': 'GRAPH',
        'category': 'Graphs',
        'pattern_key': 'graphs',
        'sources': ['neetcode'],
    },
    {
        'title': 'Open The Lock',
        'slug': 'open-the-lock',
        'difficulty': 'MEDIUM',
        'topic': 'GRAPH',
        'category': 'Graphs',
        'pattern_key': 'graphs',
        'sources': ['neetcode'],
    },
    {
        'title': 'Course Schedule IV',
        'slug': 'course-schedule-iv',
        'difficulty': 'MEDIUM',
        'topic': 'GRAPH',
        'category': 'Graphs',
        'pattern_key': 'graphs',
        'sources': ['neetcode'],
    },
    {
        'title': 'Accounts Merge',
        'slug': 'accounts-merge',
        'difficulty': 'MEDIUM',
        'topic': 'GRAPH',
        'category': 'Graphs',
        'pattern_key': 'graphs',
        'sources': ['neetcode'],
    },
    {
        'title': 'Evaluate Division',
        'slug': 'evaluate-division',
        'difficulty': 'MEDIUM',
        'topic': 'GRAPH',
        'category': 'Graphs',
        'pattern_key': 'graphs',
        'sources': ['neetcode'],
    },
    {
        'title': 'Minimum Height Trees',
        'slug': 'minimum-height-trees',
        'difficulty': 'MEDIUM',
        'topic': 'GRAPH',
        'category': 'Graphs',
        'pattern_key': 'graphs',
        'sources': ['neetcode'],
    },
    {
        'title': 'Path with Minimum Effort',
        'slug': 'path-with-minimum-effort',
        'difficulty': 'MEDIUM',
        'topic': 'GRAPH',
        'category': 'Advanced Graphs',
        'pattern_key': 'advanced-graphs',
        'sources': ['neetcode'],
    },
    {
        'title': 'Find Critical and Pseudo Critical Edges in Minimum Spanning Tree',
        'slug': 'find-critical-and-pseudo-critical-edges-in-minimum-spanning-tree',
        'difficulty': 'HARD',
        'topic': 'GRAPH',
        'category': 'Advanced Graphs',
        'pattern_key': 'advanced-graphs',
        'sources': ['neetcode'],
    },
    {
        'title': 'Build a Matrix With Conditions',
        'slug': 'build-a-matrix-with-conditions',
        'difficulty': 'HARD',
        'topic': 'GRAPH',
        'category': 'Advanced Graphs',
        'pattern_key': 'advanced-graphs',
        'sources': ['neetcode'],
    },
    {
        'title': 'Greatest Common Divisor Traversal',
        'slug': 'greatest-common-divisor-traversal',
        'difficulty': 'HARD',
        'topic': 'GRAPH',
        'category': 'Advanced Graphs',
        'pattern_key': 'advanced-graphs',
        'sources': ['neetcode'],
    },
    {
        'title': 'N-th Tribonacci Number',
        'slug': 'n-th-tribonacci-number',
        'difficulty': 'EASY',
        'topic': 'DP',
        'category': '1-D Dynamic Programming',
        'pattern_key': 'dp-1d',
        'sources': ['neetcode'],
    },
    {
        'title': 'Combination Sum IV',
        'slug': 'combination-sum-iv',
        'difficulty': 'MEDIUM',
        'topic': 'DP',
        'category': '1-D Dynamic Programming',
        'pattern_key': 'dp-1d',
        'sources': ['neetcode'],
    },
    {
        'title': 'Perfect Squares',
        'slug': 'perfect-squares',
        'difficulty': 'MEDIUM',
        'topic': 'DP',
        'category': '1-D Dynamic Programming',
        'pattern_key': 'dp-1d',
        'sources': ['neetcode'],
    },
    {
        'title': 'Integer Break',
        'slug': 'integer-break',
        'difficulty': 'MEDIUM',
        'topic': 'DP',
        'category': '1-D Dynamic Programming',
        'pattern_key': 'dp-1d',
        'sources': ['neetcode'],
    },
    {
        'title': 'Stone Game III',
        'slug': 'stone-game-iii',
        'difficulty': 'HARD',
        'topic': 'DP',
        'category': '1-D Dynamic Programming',
        'pattern_key': 'dp-1d',
        'sources': ['neetcode'],
    },
    {
        'title': 'Unique Paths II',
        'slug': 'unique-paths-ii',
        'difficulty': 'MEDIUM',
        'topic': 'DP',
        'category': '2-D Dynamic Programming',
        'pattern_key': 'dp-2d',
        'sources': ['neetcode'],
    },
    {
        'title': 'Minimum Path Sum',
        'slug': 'minimum-path-sum',
        'difficulty': 'MEDIUM',
        'topic': 'DP',
        'category': '2-D Dynamic Programming',
        'pattern_key': 'dp-2d',
        'sources': ['neetcode'],
    },
    {
        'title': 'Last Stone Weight II',
        'slug': 'last-stone-weight-ii',
        'difficulty': 'MEDIUM',
        'topic': 'DP',
        'category': '2-D Dynamic Programming',
        'pattern_key': 'dp-2d',
        'sources': ['neetcode'],
    },
    {
        'title': 'Stone Game',
        'slug': 'stone-game',
        'difficulty': 'MEDIUM',
        'topic': 'DP',
        'category': '2-D Dynamic Programming',
        'pattern_key': 'dp-2d',
        'sources': ['neetcode'],
    },
    {
        'title': 'Stone Game II',
        'slug': 'stone-game-ii',
        'difficulty': 'MEDIUM',
        'topic': 'DP',
        'category': '2-D Dynamic Programming',
        'pattern_key': 'dp-2d',
        'sources': ['neetcode'],
    },
    {
        'title': 'Lemonade Change',
        'slug': 'lemonade-change',
        'difficulty': 'EASY',
        'topic': 'ARRAY',
        'category': 'Greedy',
        'pattern_key': 'greedy',
        'sources': ['neetcode'],
    },
    {
        'title': 'Maximum Sum Circular Subarray',
        'slug': 'maximum-sum-circular-subarray',
        'difficulty': 'MEDIUM',
        'topic': 'ARRAY',
        'category': 'Greedy',
        'pattern_key': 'greedy',
        'sources': ['neetcode'],
    },
    {
        'title': 'Longest Turbulent Subarray',
        'slug': 'longest-turbulent-subarray',
        'difficulty': 'MEDIUM',
        'topic': 'ARRAY',
        'category': 'Greedy',
        'pattern_key': 'greedy',
        'sources': ['neetcode'],
    },
    {
        'title': 'Jump Game VII',
        'slug': 'jump-game-vii',
        'difficulty': 'MEDIUM',
        'topic': 'ARRAY',
        'category': 'Greedy',
        'pattern_key': 'greedy',
        'sources': ['neetcode'],
    },
    {
        'title': 'Dota2 Senate',
        'slug': 'dota2-senate',
        'difficulty': 'MEDIUM',
        'topic': 'ARRAY',
        'category': 'Greedy',
        'pattern_key': 'greedy',
        'sources': ['neetcode'],
    },
    {
        'title': 'Candy',
        'slug': 'candy',
        'difficulty': 'HARD',
        'topic': 'ARRAY',
        'category': 'Greedy',
        'pattern_key': 'greedy',
        'sources': ['neetcode'],
    },
    {
        'title': 'Meeting Rooms III',
        'slug': 'meeting-rooms-iii',
        'difficulty': 'HARD',
        'topic': 'ARRAY',
        'category': 'Intervals',
        'pattern_key': 'intervals',
        'sources': ['neetcode'],
    },
    {
        'title': 'Minimum Interval to Include Each Query',
        'slug': 'minimum-interval-to-include-each-query',
        'difficulty': 'HARD',
        'topic': 'ARRAY',
        'category': 'Intervals',
        'pattern_key': 'intervals',
        'sources': ['neetcode'],
    },
    {
        'title': 'Excel Sheet Column Title',
        'slug': 'excel-sheet-column-title',
        'difficulty': 'EASY',
        'topic': 'ARRAY',
        'category': 'Math & Geometry',
        'pattern_key': 'math-geometry',
        'sources': ['neetcode'],
    },
    {
        'title': 'Greatest Common Divisor of Strings',
        'slug': 'greatest-common-divisor-of-strings',
        'difficulty': 'EASY',
        'topic': 'ARRAY',
        'category': 'Math & Geometry',
        'pattern_key': 'math-geometry',
        'sources': ['neetcode'],
    },
    {
        'title': 'Insert Greatest Common Divisors in Linked List',
        'slug': 'insert-greatest-common-divisors-in-linked-list',
        'difficulty': 'MEDIUM',
        'topic': 'ARRAY',
        'category': 'Math & Geometry',
        'pattern_key': 'math-geometry',
        'sources': ['neetcode'],
    },
    {
        'title': 'Transpose Matrix',
        'slug': 'transpose-matrix',
        'difficulty': 'EASY',
        'topic': 'ARRAY',
        'category': 'Math & Geometry',
        'pattern_key': 'math-geometry',
        'sources': ['neetcode'],
    },
    {
        'title': 'Roman to Integer',
        'slug': 'roman-to-integer',
        'difficulty': 'EASY',
        'topic': 'ARRAY',
        'category': 'Math & Geometry',
        'pattern_key': 'math-geometry',
        'sources': ['neetcode'],
    },
    {
        'title': 'Add Binary',
        'slug': 'add-binary',
        'difficulty': 'EASY',
        'topic': 'ARRAY',
        'category': 'Bit Manipulation',
        'pattern_key': 'bit-manipulation',
        'sources': ['neetcode'],
    },
    {
        'title': 'Bitwise AND of Numbers Range',
        'slug': 'bitwise-and-of-numbers-range',
        'difficulty': 'MEDIUM',
        'topic': 'ARRAY',
        'category': 'Bit Manipulation',
        'pattern_key': 'bit-manipulation',
        'sources': ['neetcode'],
    },
    {
        'title': 'Minimum Array End',
        'slug': 'minimum-array-end',
        'difficulty': 'MEDIUM',
        'topic': 'ARRAY',
        'category': 'Bit Manipulation',
        'pattern_key': 'bit-manipulation',
        'sources': ['neetcode'],
    },
]

# Pattern -> new slugs, merged into the roadmap DAG at import time
# (see app/services/roadmap.py).
NC250_PATTERN_EXTRAS: dict[str, list[str]] = {
    'advanced-graphs': [
        'path-with-minimum-effort',
        'find-critical-and-pseudo-critical-edges-in-minimum-spanning-tree',
        'build-a-matrix-with-conditions',
        'greatest-common-divisor-traversal',
    ],
    'arrays-hashing': [
        'concatenation-of-array',
        'longest-common-prefix',
        'remove-element',
        'majority-element',
        'design-hashset',
        'design-hashmap',
        'sort-an-array',
        'sort-colors',
        'range-sum-query-2d-immutable',
        'best-time-to-buy-and-sell-stock-ii',
        'majority-element-ii',
    ],
    'backtracking': [
        'sum-of-all-subset-xor-totals',
        'combinations',
        'permutations-ii',
        'matchsticks-to-square',
        'partition-to-k-equal-sum-subsets',
        'n-queens-ii',
        'word-break-ii',
    ],
    'binary-search': [
        'search-insert-position',
        'guess-number-higher-or-lower',
        'sqrtx',
        'capacity-to-ship-packages-within-d-days',
        'search-in-rotated-sorted-array-ii',
        'split-array-largest-sum',
        'find-in-mountain-array',
    ],
    'bit-manipulation': [
        'add-binary',
        'bitwise-and-of-numbers-range',
        'minimum-array-end',
    ],
    'dp-1d': [
        'n-th-tribonacci-number',
        'combination-sum-iv',
        'perfect-squares',
        'integer-break',
        'stone-game-iii',
    ],
    'dp-2d': [
        'unique-paths-ii',
        'minimum-path-sum',
        'last-stone-weight-ii',
        'stone-game',
        'stone-game-ii',
    ],
    'graphs': [
        'island-perimeter',
        'verifying-an-alien-dictionary',
        'find-the-town-judge',
        'open-the-lock',
        'course-schedule-iv',
        'accounts-merge',
        'evaluate-division',
        'minimum-height-trees',
    ],
    'greedy': [
        'lemonade-change',
        'maximum-sum-circular-subarray',
        'longest-turbulent-subarray',
        'jump-game-vii',
        'dota2-senate',
        'candy',
    ],
    'heap-priority-queue': [
        'single-threaded-cpu',
        'reorganize-string',
        'longest-happy-string',
        'car-pooling',
        'ipo',
    ],
    'intervals': [
        'meeting-rooms-iii',
        'minimum-interval-to-include-each-query',
    ],
    'linked-list': [
        'reverse-linked-list-ii',
        'design-circular-queue',
        'lfu-cache',
    ],
    'math-geometry': [
        'excel-sheet-column-title',
        'greatest-common-divisor-of-strings',
        'insert-greatest-common-divisors-in-linked-list',
        'transpose-matrix',
        'roman-to-integer',
    ],
    'sliding-window': [
        'contains-duplicate-ii',
        'minimum-size-subarray-sum',
        'find-k-closest-elements',
    ],
    'stack': [
        'baseball-game',
        'implement-stack-using-queues',
        'implement-queue-using-stacks',
        'asteroid-collision',
        'online-stock-span',
        'simplify-path',
        'decode-string',
        'maximum-frequency-stack',
    ],
    'trees': [
        'binary-tree-inorder-traversal',
        'binary-tree-preorder-traversal',
        'binary-tree-postorder-traversal',
        'maximum-depth-of-binary-tree',
        'lowest-common-ancestor-of-a-binary-search-tree',
        'insert-into-a-binary-search-tree',
        'delete-node-in-a-bst',
        'construct-quad-tree',
        'house-robber-iii',
        'delete-leaves-with-a-given-value',
    ],
    'tries': [
        'extra-characters-in-a-string',
    ],
    'two-pointers': [
        'reverse-string',
        'valid-palindrome-ii',
        'merge-strings-alternately',
        'merge-sorted-array',
        'remove-duplicates-from-sorted-array',
        '4sum',
        'rotate-array',
        'boats-to-save-people',
    ],
}
