"""NeetCode 150 study catalog (catalog-only seed).

Each entry carries title / slug / difficulty / topic / category plus a short
description. Fully-authored problems (those already in the DB with starter code
and test cases) reuse their existing slug and are NOT overwritten here — this file
only ensures they appear in the roadmap catalog. New problems are inserted as
catalog placeholders (`starter_code={}`, `test_cases=[]`) to be authored later.
"""

NEETCODE_150: list[dict] = [
    {
        "title": 'Contains Duplicate',
        "slug": 'contains-duplicate',
        "difficulty": 'EASY',
        "topic": 'ARRAY',
        "category": 'Arrays & Hashing',
        "description": '# Contains Duplicate\n\n## Statement\nA classic easy problem in the "Arrays & Hashing" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Valid Anagram',
        "slug": 'valid-anagram',
        "difficulty": 'EASY',
        "topic": 'ARRAY',
        "category": 'Arrays & Hashing',
    },
    {
        "title": 'Two Sum',
        "slug": 'two-sum',
        "difficulty": 'EASY',
        "topic": 'ARRAY',
        "category": 'Arrays & Hashing',
    },
    {
        "title": 'Group Anagrams',
        "slug": 'group-anagrams',
        "difficulty": 'MEDIUM',
        "topic": 'ARRAY',
        "category": 'Arrays & Hashing',
    },
    {
        "title": 'Top K Frequent Elements',
        "slug": 'top-k-frequent-elements',
        "difficulty": 'MEDIUM',
        "topic": 'ARRAY',
        "category": 'Arrays & Hashing',
        "description": '# Top K Frequent Elements\n\n## Statement\nA classic medium problem in the "Arrays & Hashing" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Product of Array Except Self',
        "slug": 'product-of-array-except-self',
        "difficulty": 'MEDIUM',
        "topic": 'ARRAY',
        "category": 'Arrays & Hashing',
    },
    {
        "title": 'Valid Sudoku',
        "slug": 'valid-sudoku',
        "difficulty": 'MEDIUM',
        "topic": 'ARRAY',
        "category": 'Arrays & Hashing',
        "description": '# Valid Sudoku\n\n## Statement\nA classic medium problem in the "Arrays & Hashing" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Encode and Decode Strings',
        "slug": 'encode-and-decode-strings',
        "difficulty": 'MEDIUM',
        "topic": 'ARRAY',
        "category": 'Arrays & Hashing',
        "description": '# Encode and Decode Strings\n\n## Statement\nA classic medium problem in the "Arrays & Hashing" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Longest Consecutive Sequence',
        "slug": 'longest-consecutive-sequence',
        "difficulty": 'MEDIUM',
        "topic": 'ARRAY',
        "category": 'Arrays & Hashing',
        "description": '# Longest Consecutive Sequence\n\n## Statement\nA classic medium problem in the "Arrays & Hashing" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Valid Palindrome',
        "slug": 'valid-palindrome',
        "difficulty": 'EASY',
        "topic": 'ARRAY',
        "category": 'Two Pointers',
    },
    {
        "title": 'Two Sum II - Input Array Is Sorted',
        "slug": 'two-sum-ii-input-array-is-sorted',
        "difficulty": 'MEDIUM',
        "topic": 'ARRAY',
        "category": 'Two Pointers',
        "description": '# Two Sum II - Input Array Is Sorted\n\n## Statement\nA classic medium problem in the "Two Pointers" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": '3Sum',
        "slug": '3sum',
        "difficulty": 'MEDIUM',
        "topic": 'ARRAY',
        "category": 'Two Pointers',
        "description": '# 3Sum\n\n## Statement\nA classic medium problem in the "Two Pointers" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Container With Most Water',
        "slug": 'container-with-most-water',
        "difficulty": 'MEDIUM',
        "topic": 'ARRAY',
        "category": 'Two Pointers',
        "description": '# Container With Most Water\n\n## Statement\nA classic medium problem in the "Two Pointers" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Trapping Rain Water',
        "slug": 'trapping-rain-water',
        "difficulty": 'HARD',
        "topic": 'ARRAY',
        "category": 'Two Pointers',
        "description": '# Trapping Rain Water\n\n## Statement\nA classic hard problem in the "Two Pointers" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Best Time to Buy and Sell Stock',
        "slug": 'best-time-to-buy-and-sell-stock',
        "difficulty": 'EASY',
        "topic": 'STRING',
        "category": 'Sliding Window',
        "description": '# Best Time to Buy and Sell Stock\n\n## Statement\nA classic easy problem in the "Sliding Window" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Longest Substring Without Repeating Characters',
        "slug": 'longest-substring-without-repeating-characters',
        "difficulty": 'MEDIUM',
        "topic": 'STRING',
        "category": 'Sliding Window',
    },
    {
        "title": 'Longest Repeating Character Replacement',
        "slug": 'longest-repeating-character-replacement',
        "difficulty": 'MEDIUM',
        "topic": 'STRING',
        "category": 'Sliding Window',
        "description": '# Longest Repeating Character Replacement\n\n## Statement\nA classic medium problem in the "Sliding Window" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Permutation in String',
        "slug": 'permutation-in-string',
        "difficulty": 'MEDIUM',
        "topic": 'STRING',
        "category": 'Sliding Window',
        "description": '# Permutation in String\n\n## Statement\nA classic medium problem in the "Sliding Window" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Minimum Window Substring',
        "slug": 'minimum-window-substring',
        "difficulty": 'HARD',
        "topic": 'STRING',
        "category": 'Sliding Window',
    },
    {
        "title": 'Sliding Window Maximum',
        "slug": 'sliding-window-maximum',
        "difficulty": 'HARD',
        "topic": 'STRING',
        "category": 'Sliding Window',
    },
    {
        "title": 'Valid Parentheses',
        "slug": 'valid-parentheses',
        "difficulty": 'EASY',
        "topic": 'STACK',
        "category": 'Stack',
    },
    {
        "title": 'Min Stack',
        "slug": 'min-stack',
        "difficulty": 'MEDIUM',
        "topic": 'STACK',
        "category": 'Stack',
        "description": '# Min Stack\n\n## Statement\nA classic medium problem in the "Stack" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Evaluate Reverse Polish Notation',
        "slug": 'evaluate-reverse-polish-notation',
        "difficulty": 'MEDIUM',
        "topic": 'STACK',
        "category": 'Stack',
        "description": '# Evaluate Reverse Polish Notation\n\n## Statement\nA classic medium problem in the "Stack" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Generate Parentheses',
        "slug": 'generate-parentheses',
        "difficulty": 'MEDIUM',
        "topic": 'STACK',
        "category": 'Stack',
        "description": '# Generate Parentheses\n\n## Statement\nA classic medium problem in the "Stack" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Daily Temperatures',
        "slug": 'daily-temperatures',
        "difficulty": 'MEDIUM',
        "topic": 'STACK',
        "category": 'Stack',
    },
    {
        "title": 'Car Fleet',
        "slug": 'car-fleet',
        "difficulty": 'MEDIUM',
        "topic": 'STACK',
        "category": 'Stack',
        "description": '# Car Fleet\n\n## Statement\nA classic medium problem in the "Stack" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Largest Rectangle in Histogram',
        "slug": 'largest-rectangle-in-histogram',
        "difficulty": 'HARD',
        "topic": 'STACK',
        "category": 'Stack',
        "description": '# Largest Rectangle in Histogram\n\n## Statement\nA classic hard problem in the "Stack" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Binary Search',
        "slug": 'binary-search',
        "difficulty": 'EASY',
        "topic": 'ARRAY',
        "category": 'Binary Search',
        "description": '# Binary Search\n\n## Statement\nA classic easy problem in the "Binary Search" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Search a 2D Matrix',
        "slug": 'search-a-2d-matrix',
        "difficulty": 'MEDIUM',
        "topic": 'ARRAY',
        "category": 'Binary Search',
        "description": '# Search a 2D Matrix\n\n## Statement\nA classic medium problem in the "Binary Search" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Koko Eating Bananas',
        "slug": 'koko-eating-bananas',
        "difficulty": 'MEDIUM',
        "topic": 'ARRAY',
        "category": 'Binary Search',
        "description": '# Koko Eating Bananas\n\n## Statement\nA classic medium problem in the "Binary Search" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Find Minimum in Rotated Sorted Array',
        "slug": 'find-minimum-in-rotated-sorted-array',
        "difficulty": 'MEDIUM',
        "topic": 'ARRAY',
        "category": 'Binary Search',
        "description": '# Find Minimum in Rotated Sorted Array\n\n## Statement\nA classic medium problem in the "Binary Search" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Search in Rotated Sorted Array',
        "slug": 'search-in-rotated-sorted-array',
        "difficulty": 'MEDIUM',
        "topic": 'ARRAY',
        "category": 'Binary Search',
        "description": '# Search in Rotated Sorted Array\n\n## Statement\nA classic medium problem in the "Binary Search" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Time Based Key-Value Store',
        "slug": 'time-based-key-value-store',
        "difficulty": 'MEDIUM',
        "topic": 'ARRAY',
        "category": 'Binary Search',
        "description": '# Time Based Key-Value Store\n\n## Statement\nA classic medium problem in the "Binary Search" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Median of Two Sorted Arrays',
        "slug": 'median-of-two-sorted-arrays',
        "difficulty": 'HARD',
        "topic": 'ARRAY',
        "category": 'Binary Search',
        "description": '# Median of Two Sorted Arrays\n\n## Statement\nA classic hard problem in the "Binary Search" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Reverse Linked List',
        "slug": 'reverse-linked-list',
        "difficulty": 'EASY',
        "topic": 'LINKED_LIST',
        "category": 'Linked List',
    },
    {
        "title": 'Merge Two Sorted Lists',
        "slug": 'merge-two-sorted-lists',
        "difficulty": 'EASY',
        "topic": 'LINKED_LIST',
        "category": 'Linked List',
    },
    {
        "title": 'Reorder List',
        "slug": 'reorder-list',
        "difficulty": 'MEDIUM',
        "topic": 'LINKED_LIST',
        "category": 'Linked List',
        "description": '# Reorder List\n\n## Statement\nA classic medium problem in the "Linked List" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Remove Nth Node From End of List',
        "slug": 'remove-nth-node-from-end-of-list',
        "difficulty": 'MEDIUM',
        "topic": 'LINKED_LIST',
        "category": 'Linked List',
        "description": '# Remove Nth Node From End of List\n\n## Statement\nA classic medium problem in the "Linked List" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Copy List with Random Pointer',
        "slug": 'copy-list-with-random-pointer',
        "difficulty": 'MEDIUM',
        "topic": 'LINKED_LIST',
        "category": 'Linked List',
        "description": '# Copy List with Random Pointer\n\n## Statement\nA classic medium problem in the "Linked List" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Add Two Numbers',
        "slug": 'add-two-numbers',
        "difficulty": 'MEDIUM',
        "topic": 'LINKED_LIST',
        "category": 'Linked List',
        "description": '# Add Two Numbers\n\n## Statement\nA classic medium problem in the "Linked List" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Linked List Cycle',
        "slug": 'linked-list-cycle',
        "difficulty": 'EASY',
        "topic": 'LINKED_LIST',
        "category": 'Linked List',
    },
    {
        "title": 'Find the Duplicate Number',
        "slug": 'find-the-duplicate-number',
        "difficulty": 'MEDIUM',
        "topic": 'LINKED_LIST',
        "category": 'Linked List',
        "description": '# Find the Duplicate Number\n\n## Statement\nA classic medium problem in the "Linked List" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'LRU Cache',
        "slug": 'lru-cache',
        "difficulty": 'MEDIUM',
        "topic": 'LINKED_LIST',
        "category": 'Linked List',
        "description": '# LRU Cache\n\n## Statement\nA classic medium problem in the "Linked List" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Merge k Sorted Lists',
        "slug": 'merge-k-sorted-lists',
        "difficulty": 'HARD',
        "topic": 'LINKED_LIST',
        "category": 'Linked List',
        "description": '# Merge k Sorted Lists\n\n## Statement\nA classic hard problem in the "Linked List" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Reverse Nodes in k-Group',
        "slug": 'reverse-nodes-in-k-group',
        "difficulty": 'HARD',
        "topic": 'LINKED_LIST',
        "category": 'Linked List',
        "description": '# Reverse Nodes in k-Group\n\n## Statement\nA classic hard problem in the "Linked List" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Invert Binary Tree',
        "slug": 'invert-binary-tree',
        "difficulty": 'EASY',
        "topic": 'TREE',
        "category": 'Trees',
    },
    {
        "title": 'Maximum Depth of Binary Tree',
        "slug": 'maximum-depth-binary-tree',
        "difficulty": 'EASY',
        "topic": 'TREE',
        "category": 'Trees',
    },
    {
        "title": 'Diameter of Binary Tree',
        "slug": 'diameter-of-binary-tree',
        "difficulty": 'EASY',
        "topic": 'TREE',
        "category": 'Trees',
    },
    {
        "title": 'Balanced Binary Tree',
        "slug": 'balanced-binary-tree',
        "difficulty": 'EASY',
        "topic": 'TREE',
        "category": 'Trees',
        "description": '# Balanced Binary Tree\n\n## Statement\nA classic easy problem in the "Trees" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Same Tree',
        "slug": 'same-tree',
        "difficulty": 'EASY',
        "topic": 'TREE',
        "category": 'Trees',
        "description": '# Same Tree\n\n## Statement\nA classic easy problem in the "Trees" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Subtree of Another Tree',
        "slug": 'subtree-of-another-tree',
        "difficulty": 'EASY',
        "topic": 'TREE',
        "category": 'Trees',
        "description": '# Subtree of Another Tree\n\n## Statement\nA classic easy problem in the "Trees" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Lowest Common Ancestor of a Binary Search Tree',
        "slug": 'lowest-common-ancestor-bst',
        "difficulty": 'MEDIUM',
        "topic": 'TREE',
        "category": 'Trees',
    },
    {
        "title": 'Binary Tree Level Order Traversal',
        "slug": 'binary-tree-level-order-traversal',
        "difficulty": 'MEDIUM',
        "topic": 'TREE',
        "category": 'Trees',
    },
    {
        "title": 'Binary Tree Right Side View',
        "slug": 'binary-tree-right-side-view',
        "difficulty": 'MEDIUM',
        "topic": 'TREE',
        "category": 'Trees',
        "description": '# Binary Tree Right Side View\n\n## Statement\nA classic medium problem in the "Trees" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Count Good Nodes in Binary Tree',
        "slug": 'count-good-nodes-in-binary-tree',
        "difficulty": 'MEDIUM',
        "topic": 'TREE',
        "category": 'Trees',
        "description": '# Count Good Nodes in Binary Tree\n\n## Statement\nA classic medium problem in the "Trees" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Validate Binary Search Tree',
        "slug": 'validate-binary-search-tree',
        "difficulty": 'MEDIUM',
        "topic": 'TREE',
        "category": 'Trees',
    },
    {
        "title": 'Kth Smallest Element in a BST',
        "slug": 'kth-smallest-element-in-a-bst',
        "difficulty": 'MEDIUM',
        "topic": 'TREE',
        "category": 'Trees',
        "description": '# Kth Smallest Element in a BST\n\n## Statement\nA classic medium problem in the "Trees" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Construct Binary Tree from Preorder and Inorder Traversal',
        "slug": 'construct-binary-tree-from-preorder-and-inorder-traversal',
        "difficulty": 'MEDIUM',
        "topic": 'TREE',
        "category": 'Trees',
        "description": '# Construct Binary Tree from Preorder and Inorder Traversal\n\n## Statement\nA classic medium problem in the "Trees" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Binary Tree Maximum Path Sum',
        "slug": 'binary-tree-maximum-path-sum',
        "difficulty": 'HARD',
        "topic": 'TREE',
        "category": 'Trees',
        "description": '# Binary Tree Maximum Path Sum\n\n## Statement\nA classic hard problem in the "Trees" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Serialize and Deserialize Binary Tree',
        "slug": 'serialize-and-deserialize-binary-tree',
        "difficulty": 'HARD',
        "topic": 'TREE',
        "category": 'Trees',
        "description": '# Serialize and Deserialize Binary Tree\n\n## Statement\nA classic hard problem in the "Trees" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Implement Trie (Prefix Tree)',
        "slug": 'implement-trie-prefix-tree',
        "difficulty": 'MEDIUM',
        "topic": 'TREE',
        "category": 'Tries',
        "description": '# Implement Trie (Prefix Tree)\n\n## Statement\nA classic medium problem in the "Tries" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Design Add and Search Words Data Structure',
        "slug": 'design-add-and-search-words-data-structure',
        "difficulty": 'MEDIUM',
        "topic": 'TREE',
        "category": 'Tries',
        "description": '# Design Add and Search Words Data Structure\n\n## Statement\nA classic medium problem in the "Tries" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Word Search II',
        "slug": 'word-search-ii',
        "difficulty": 'HARD',
        "topic": 'TREE',
        "category": 'Tries',
        "description": '# Word Search II\n\n## Statement\nA classic hard problem in the "Tries" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Kth Largest Element in a Stream',
        "slug": 'kth-largest-element-in-a-stream',
        "difficulty": 'EASY',
        "topic": 'QUEUE',
        "category": 'Heap / Priority Queue',
        "description": '# Kth Largest Element in a Stream\n\n## Statement\nA classic easy problem in the "Heap / Priority Queue" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Last Stone Weight',
        "slug": 'last-stone-weight',
        "difficulty": 'EASY',
        "topic": 'QUEUE',
        "category": 'Heap / Priority Queue',
        "description": '# Last Stone Weight\n\n## Statement\nA classic easy problem in the "Heap / Priority Queue" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'K Closest Points to Origin',
        "slug": 'k-closest-points-to-origin',
        "difficulty": 'MEDIUM',
        "topic": 'QUEUE',
        "category": 'Heap / Priority Queue',
        "description": '# K Closest Points to Origin\n\n## Statement\nA classic medium problem in the "Heap / Priority Queue" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Kth Largest Element in an Array',
        "slug": 'kth-largest-element-in-an-array',
        "difficulty": 'MEDIUM',
        "topic": 'QUEUE',
        "category": 'Heap / Priority Queue',
        "description": '# Kth Largest Element in an Array\n\n## Statement\nA classic medium problem in the "Heap / Priority Queue" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Task Scheduler',
        "slug": 'task-scheduler',
        "difficulty": 'MEDIUM',
        "topic": 'QUEUE',
        "category": 'Heap / Priority Queue',
        "description": '# Task Scheduler\n\n## Statement\nA classic medium problem in the "Heap / Priority Queue" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Design Twitter',
        "slug": 'design-twitter',
        "difficulty": 'MEDIUM',
        "topic": 'QUEUE',
        "category": 'Heap / Priority Queue',
        "description": '# Design Twitter\n\n## Statement\nA classic medium problem in the "Heap / Priority Queue" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Find Median from Data Stream',
        "slug": 'find-median-from-data-stream',
        "difficulty": 'HARD',
        "topic": 'QUEUE',
        "category": 'Heap / Priority Queue',
        "description": '# Find Median from Data Stream\n\n## Statement\nA classic hard problem in the "Heap / Priority Queue" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Subsets',
        "slug": 'subsets',
        "difficulty": 'MEDIUM',
        "topic": 'ARRAY',
        "category": 'Backtracking',
        "description": '# Subsets\n\n## Statement\nA classic medium problem in the "Backtracking" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Combination Sum',
        "slug": 'combination-sum',
        "difficulty": 'MEDIUM',
        "topic": 'ARRAY',
        "category": 'Backtracking',
        "description": '# Combination Sum\n\n## Statement\nA classic medium problem in the "Backtracking" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Permutations',
        "slug": 'permutations',
        "difficulty": 'MEDIUM',
        "topic": 'ARRAY',
        "category": 'Backtracking',
        "description": '# Permutations\n\n## Statement\nA classic medium problem in the "Backtracking" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Subsets II',
        "slug": 'subsets-ii',
        "difficulty": 'MEDIUM',
        "topic": 'ARRAY',
        "category": 'Backtracking',
        "description": '# Subsets II\n\n## Statement\nA classic medium problem in the "Backtracking" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Combination Sum II',
        "slug": 'combination-sum-ii',
        "difficulty": 'MEDIUM',
        "topic": 'ARRAY',
        "category": 'Backtracking',
        "description": '# Combination Sum II\n\n## Statement\nA classic medium problem in the "Backtracking" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Word Search',
        "slug": 'word-search',
        "difficulty": 'MEDIUM',
        "topic": 'ARRAY',
        "category": 'Backtracking',
        "description": '# Word Search\n\n## Statement\nA classic medium problem in the "Backtracking" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Palindrome Partitioning',
        "slug": 'palindrome-partitioning',
        "difficulty": 'MEDIUM',
        "topic": 'ARRAY',
        "category": 'Backtracking',
        "description": '# Palindrome Partitioning\n\n## Statement\nA classic medium problem in the "Backtracking" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Letter Combinations of a Phone Number',
        "slug": 'letter-combinations-of-a-phone-number',
        "difficulty": 'MEDIUM',
        "topic": 'ARRAY',
        "category": 'Backtracking',
        "description": '# Letter Combinations of a Phone Number\n\n## Statement\nA classic medium problem in the "Backtracking" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'N-Queens',
        "slug": 'n-queens',
        "difficulty": 'HARD',
        "topic": 'ARRAY',
        "category": 'Backtracking',
        "description": '# N-Queens\n\n## Statement\nA classic hard problem in the "Backtracking" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Number of Islands',
        "slug": 'number-of-islands',
        "difficulty": 'MEDIUM',
        "topic": 'GRAPH',
        "category": 'Graphs',
    },
    {
        "title": 'Clone Graph',
        "slug": 'clone-graph',
        "difficulty": 'MEDIUM',
        "topic": 'GRAPH',
        "category": 'Graphs',
        "description": '# Clone Graph\n\n## Statement\nA classic medium problem in the "Graphs" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Max Area of Island',
        "slug": 'max-area-of-island',
        "difficulty": 'MEDIUM',
        "topic": 'GRAPH',
        "category": 'Graphs',
        "description": '# Max Area of Island\n\n## Statement\nA classic medium problem in the "Graphs" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Pacific Atlantic Water Flow',
        "slug": 'pacific-atlantic-water-flow',
        "difficulty": 'MEDIUM',
        "topic": 'GRAPH',
        "category": 'Graphs',
        "description": '# Pacific Atlantic Water Flow\n\n## Statement\nA classic medium problem in the "Graphs" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Surrounded Regions',
        "slug": 'surrounded-regions',
        "difficulty": 'MEDIUM',
        "topic": 'GRAPH',
        "category": 'Graphs',
        "description": '# Surrounded Regions\n\n## Statement\nA classic medium problem in the "Graphs" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Rotting Oranges',
        "slug": 'rotting-oranges',
        "difficulty": 'MEDIUM',
        "topic": 'GRAPH',
        "category": 'Graphs',
        "description": '# Rotting Oranges\n\n## Statement\nA classic medium problem in the "Graphs" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Walls and Gates',
        "slug": 'walls-and-gates',
        "difficulty": 'MEDIUM',
        "topic": 'GRAPH',
        "category": 'Graphs',
        "description": '# Walls and Gates\n\n## Statement\nA classic medium problem in the "Graphs" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Course Schedule',
        "slug": 'course-schedule',
        "difficulty": 'MEDIUM',
        "topic": 'GRAPH',
        "category": 'Graphs',
    },
    {
        "title": 'Course Schedule II',
        "slug": 'course-schedule-ii',
        "difficulty": 'MEDIUM',
        "topic": 'GRAPH',
        "category": 'Graphs',
        "description": '# Course Schedule II\n\n## Statement\nA classic medium problem in the "Graphs" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Redundant Connection',
        "slug": 'redundant-connection',
        "difficulty": 'MEDIUM',
        "topic": 'GRAPH',
        "category": 'Graphs',
        "description": '# Redundant Connection\n\n## Statement\nA classic medium problem in the "Graphs" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Number of Connected Components in an Undirected Graph',
        "slug": 'number-of-connected-components-in-an-undirected-graph',
        "difficulty": 'MEDIUM',
        "topic": 'GRAPH',
        "category": 'Graphs',
        "description": '# Number of Connected Components in an Undirected Graph\n\n## Statement\nA classic medium problem in the "Graphs" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Graph Valid Tree',
        "slug": 'graph-valid-tree',
        "difficulty": 'MEDIUM',
        "topic": 'GRAPH',
        "category": 'Graphs',
        "description": '# Graph Valid Tree\n\n## Statement\nA classic medium problem in the "Graphs" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Word Ladder',
        "slug": 'word-ladder',
        "difficulty": 'HARD',
        "topic": 'GRAPH',
        "category": 'Graphs',
        "description": '# Word Ladder\n\n## Statement\nA classic hard problem in the "Graphs" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Reconstruct Itinerary',
        "slug": 'reconstruct-itinerary',
        "difficulty": 'HARD',
        "topic": 'GRAPH',
        "category": 'Advanced Graphs',
        "description": '# Reconstruct Itinerary\n\n## Statement\nA classic hard problem in the "Advanced Graphs" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Min Cost to Connect All Points',
        "slug": 'min-cost-to-connect-all-points',
        "difficulty": 'MEDIUM',
        "topic": 'GRAPH',
        "category": 'Advanced Graphs',
        "description": '# Min Cost to Connect All Points\n\n## Statement\nA classic medium problem in the "Advanced Graphs" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Network Delay Time',
        "slug": 'network-delay-time',
        "difficulty": 'MEDIUM',
        "topic": 'GRAPH',
        "category": 'Advanced Graphs',
        "description": '# Network Delay Time\n\n## Statement\nA classic medium problem in the "Advanced Graphs" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Swim in Rising Water',
        "slug": 'swim-in-rising-water',
        "difficulty": 'HARD',
        "topic": 'GRAPH',
        "category": 'Advanced Graphs',
        "description": '# Swim in Rising Water\n\n## Statement\nA classic hard problem in the "Advanced Graphs" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Alien Dictionary',
        "slug": 'alien-dictionary',
        "difficulty": 'HARD',
        "topic": 'GRAPH',
        "category": 'Advanced Graphs',
        "description": '# Alien Dictionary\n\n## Statement\nA classic hard problem in the "Advanced Graphs" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Cheapest Flights Within K Stops',
        "slug": 'cheapest-flights-within-k-stops',
        "difficulty": 'MEDIUM',
        "topic": 'GRAPH',
        "category": 'Advanced Graphs',
        "description": '# Cheapest Flights Within K Stops\n\n## Statement\nA classic medium problem in the "Advanced Graphs" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Climbing Stairs',
        "slug": 'climbing-stairs',
        "difficulty": 'EASY',
        "topic": 'DP',
        "category": '1-D Dynamic Programming',
    },
    {
        "title": 'Min Cost Climbing Stairs',
        "slug": 'min-cost-climbing-stairs',
        "difficulty": 'EASY',
        "topic": 'DP',
        "category": '1-D Dynamic Programming',
        "description": '# Min Cost Climbing Stairs\n\n## Statement\nA classic easy problem in the "1-D Dynamic Programming" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'House Robber',
        "slug": 'house-robber',
        "difficulty": 'MEDIUM',
        "topic": 'DP',
        "category": '1-D Dynamic Programming',
        "description": '# House Robber\n\n## Statement\nA classic medium problem in the "1-D Dynamic Programming" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'House Robber II',
        "slug": 'house-robber-ii',
        "difficulty": 'MEDIUM',
        "topic": 'DP',
        "category": '1-D Dynamic Programming',
        "description": '# House Robber II\n\n## Statement\nA classic medium problem in the "1-D Dynamic Programming" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Longest Palindromic Substring',
        "slug": 'longest-palindromic-substring',
        "difficulty": 'MEDIUM',
        "topic": 'DP',
        "category": '1-D Dynamic Programming',
        "description": '# Longest Palindromic Substring\n\n## Statement\nA classic medium problem in the "1-D Dynamic Programming" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Palindromic Substrings',
        "slug": 'palindromic-substrings',
        "difficulty": 'MEDIUM',
        "topic": 'DP',
        "category": '1-D Dynamic Programming',
        "description": '# Palindromic Substrings\n\n## Statement\nA classic medium problem in the "1-D Dynamic Programming" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Decode Ways',
        "slug": 'decode-ways',
        "difficulty": 'MEDIUM',
        "topic": 'DP',
        "category": '1-D Dynamic Programming',
        "description": '# Decode Ways\n\n## Statement\nA classic medium problem in the "1-D Dynamic Programming" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Coin Change',
        "slug": 'coin-change',
        "difficulty": 'MEDIUM',
        "topic": 'DP',
        "category": '1-D Dynamic Programming',
    },
    {
        "title": 'Maximum Product Subarray',
        "slug": 'maximum-product-subarray',
        "difficulty": 'MEDIUM',
        "topic": 'DP',
        "category": '1-D Dynamic Programming',
        "description": '# Maximum Product Subarray\n\n## Statement\nA classic medium problem in the "1-D Dynamic Programming" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Word Break',
        "slug": 'word-break',
        "difficulty": 'MEDIUM',
        "topic": 'DP',
        "category": '1-D Dynamic Programming',
    },
    {
        "title": 'Longest Increasing Subsequence',
        "slug": 'longest-increasing-subsequence',
        "difficulty": 'MEDIUM',
        "topic": 'DP',
        "category": '1-D Dynamic Programming',
    },
    {
        "title": 'Partition Equal Subset Sum',
        "slug": 'partition-equal-subset-sum',
        "difficulty": 'MEDIUM',
        "topic": 'DP',
        "category": '1-D Dynamic Programming',
        "description": '# Partition Equal Subset Sum\n\n## Statement\nA classic medium problem in the "1-D Dynamic Programming" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Unique Paths',
        "slug": 'unique-paths',
        "difficulty": 'MEDIUM',
        "topic": 'DP',
        "category": '2-D Dynamic Programming',
    },
    {
        "title": 'Longest Common Subsequence',
        "slug": 'longest-common-subsequence',
        "difficulty": 'MEDIUM',
        "topic": 'DP',
        "category": '2-D Dynamic Programming',
        "description": '# Longest Common Subsequence\n\n## Statement\nA classic medium problem in the "2-D Dynamic Programming" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Best Time to Buy and Sell Stock with Cooldown',
        "slug": 'best-time-to-buy-and-sell-stock-with-cooldown',
        "difficulty": 'MEDIUM',
        "topic": 'DP',
        "category": '2-D Dynamic Programming',
        "description": '# Best Time to Buy and Sell Stock with Cooldown\n\n## Statement\nA classic medium problem in the "2-D Dynamic Programming" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Coin Change II',
        "slug": 'coin-change-ii',
        "difficulty": 'MEDIUM',
        "topic": 'DP',
        "category": '2-D Dynamic Programming',
        "description": '# Coin Change II\n\n## Statement\nA classic medium problem in the "2-D Dynamic Programming" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Target Sum',
        "slug": 'target-sum',
        "difficulty": 'MEDIUM',
        "topic": 'DP',
        "category": '2-D Dynamic Programming',
        "description": '# Target Sum\n\n## Statement\nA classic medium problem in the "2-D Dynamic Programming" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Interleaving String',
        "slug": 'interleaving-string',
        "difficulty": 'MEDIUM',
        "topic": 'DP',
        "category": '2-D Dynamic Programming',
        "description": '# Interleaving String\n\n## Statement\nA classic medium problem in the "2-D Dynamic Programming" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Longest Increasing Path in a Matrix',
        "slug": 'longest-increasing-path-in-a-matrix',
        "difficulty": 'HARD',
        "topic": 'DP',
        "category": '2-D Dynamic Programming',
        "description": '# Longest Increasing Path in a Matrix\n\n## Statement\nA classic hard problem in the "2-D Dynamic Programming" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Distinct Subsequences',
        "slug": 'distinct-subsequences',
        "difficulty": 'HARD',
        "topic": 'DP',
        "category": '2-D Dynamic Programming',
        "description": '# Distinct Subsequences\n\n## Statement\nA classic hard problem in the "2-D Dynamic Programming" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Edit Distance',
        "slug": 'edit-distance',
        "difficulty": 'MEDIUM',
        "topic": 'DP',
        "category": '2-D Dynamic Programming',
    },
    {
        "title": 'Burst Balloons',
        "slug": 'burst-balloons',
        "difficulty": 'HARD',
        "topic": 'DP',
        "category": '2-D Dynamic Programming',
        "description": '# Burst Balloons\n\n## Statement\nA classic hard problem in the "2-D Dynamic Programming" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Regular Expression Matching',
        "slug": 'regular-expression-matching',
        "difficulty": 'HARD',
        "topic": 'DP',
        "category": '2-D Dynamic Programming',
        "description": '# Regular Expression Matching\n\n## Statement\nA classic hard problem in the "2-D Dynamic Programming" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Maximum Subarray',
        "slug": 'maximum-subarray',
        "difficulty": 'MEDIUM',
        "topic": 'ARRAY',
        "category": 'Greedy',
    },
    {
        "title": 'Jump Game',
        "slug": 'jump-game',
        "difficulty": 'MEDIUM',
        "topic": 'ARRAY',
        "category": 'Greedy',
        "description": '# Jump Game\n\n## Statement\nA classic medium problem in the "Greedy" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Jump Game II',
        "slug": 'jump-game-ii',
        "difficulty": 'MEDIUM',
        "topic": 'ARRAY',
        "category": 'Greedy',
        "description": '# Jump Game II\n\n## Statement\nA classic medium problem in the "Greedy" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Gas Station',
        "slug": 'gas-station',
        "difficulty": 'MEDIUM',
        "topic": 'ARRAY',
        "category": 'Greedy',
        "description": '# Gas Station\n\n## Statement\nA classic medium problem in the "Greedy" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Hand of Straights',
        "slug": 'hand-of-straights',
        "difficulty": 'MEDIUM',
        "topic": 'ARRAY',
        "category": 'Greedy',
        "description": '# Hand of Straights\n\n## Statement\nA classic medium problem in the "Greedy" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Merge Triplets to Form Target Triplet',
        "slug": 'merge-triplets-to-form-target-triplet',
        "difficulty": 'MEDIUM',
        "topic": 'ARRAY',
        "category": 'Greedy',
        "description": '# Merge Triplets to Form Target Triplet\n\n## Statement\nA classic medium problem in the "Greedy" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Partition Labels',
        "slug": 'partition-labels',
        "difficulty": 'MEDIUM',
        "topic": 'ARRAY',
        "category": 'Greedy',
        "description": '# Partition Labels\n\n## Statement\nA classic medium problem in the "Greedy" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Valid Parenthesis String',
        "slug": 'valid-parenthesis-string',
        "difficulty": 'MEDIUM',
        "topic": 'ARRAY',
        "category": 'Greedy',
        "description": '# Valid Parenthesis String\n\n## Statement\nA classic medium problem in the "Greedy" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Insert Interval',
        "slug": 'insert-interval',
        "difficulty": 'MEDIUM',
        "topic": 'ARRAY',
        "category": 'Intervals',
        "description": '# Insert Interval\n\n## Statement\nA classic medium problem in the "Intervals" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Merge Intervals',
        "slug": 'merge-intervals',
        "difficulty": 'MEDIUM',
        "topic": 'ARRAY',
        "category": 'Intervals',
        "description": '# Merge Intervals\n\n## Statement\nA classic medium problem in the "Intervals" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Non-overlapping Intervals',
        "slug": 'non-overlapping-intervals',
        "difficulty": 'MEDIUM',
        "topic": 'ARRAY',
        "category": 'Intervals',
        "description": '# Non-overlapping Intervals\n\n## Statement\nA classic medium problem in the "Intervals" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Meeting Rooms',
        "slug": 'meeting-rooms',
        "difficulty": 'EASY',
        "topic": 'ARRAY',
        "category": 'Intervals',
        "description": '# Meeting Rooms\n\n## Statement\nA classic easy problem in the "Intervals" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Meeting Rooms II',
        "slug": 'meeting-rooms-ii',
        "difficulty": 'MEDIUM',
        "topic": 'ARRAY',
        "category": 'Intervals',
        "description": '# Meeting Rooms II\n\n## Statement\nA classic medium problem in the "Intervals" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Rotate Image',
        "slug": 'rotate-image',
        "difficulty": 'MEDIUM',
        "topic": 'ARRAY',
        "category": 'Math & Geometry',
        "description": '# Rotate Image\n\n## Statement\nA classic medium problem in the "Math & Geometry" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Spiral Matrix',
        "slug": 'spiral-matrix',
        "difficulty": 'MEDIUM',
        "topic": 'ARRAY',
        "category": 'Math & Geometry',
        "description": '# Spiral Matrix\n\n## Statement\nA classic medium problem in the "Math & Geometry" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Set Matrix Zeroes',
        "slug": 'set-matrix-zeroes',
        "difficulty": 'MEDIUM',
        "topic": 'ARRAY',
        "category": 'Math & Geometry',
        "description": '# Set Matrix Zeroes\n\n## Statement\nA classic medium problem in the "Math & Geometry" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Happy Number',
        "slug": 'happy-number',
        "difficulty": 'EASY',
        "topic": 'ARRAY',
        "category": 'Math & Geometry',
        "description": '# Happy Number\n\n## Statement\nA classic easy problem in the "Math & Geometry" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Plus One',
        "slug": 'plus-one',
        "difficulty": 'EASY',
        "topic": 'ARRAY',
        "category": 'Math & Geometry',
        "description": '# Plus One\n\n## Statement\nA classic easy problem in the "Math & Geometry" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Pow(x, n)',
        "slug": 'powx-n',
        "difficulty": 'MEDIUM',
        "topic": 'ARRAY',
        "category": 'Math & Geometry',
        "description": '# Pow(x, n)\n\n## Statement\nA classic medium problem in the "Math & Geometry" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Multiply Strings',
        "slug": 'multiply-strings',
        "difficulty": 'MEDIUM',
        "topic": 'ARRAY',
        "category": 'Math & Geometry',
        "description": '# Multiply Strings\n\n## Statement\nA classic medium problem in the "Math & Geometry" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Detect Squares',
        "slug": 'detect-squares',
        "difficulty": 'MEDIUM',
        "topic": 'ARRAY',
        "category": 'Math & Geometry',
        "description": '# Detect Squares\n\n## Statement\nA classic medium problem in the "Math & Geometry" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Single Number',
        "slug": 'single-number',
        "difficulty": 'EASY',
        "topic": 'ARRAY',
        "category": 'Bit Manipulation',
        "description": '# Single Number\n\n## Statement\nA classic easy problem in the "Bit Manipulation" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Number of 1 Bits',
        "slug": 'number-of-1-bits',
        "difficulty": 'EASY',
        "topic": 'ARRAY',
        "category": 'Bit Manipulation',
        "description": '# Number of 1 Bits\n\n## Statement\nA classic easy problem in the "Bit Manipulation" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Counting Bits',
        "slug": 'counting-bits',
        "difficulty": 'EASY',
        "topic": 'ARRAY',
        "category": 'Bit Manipulation',
        "description": '# Counting Bits\n\n## Statement\nA classic easy problem in the "Bit Manipulation" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Reverse Bits',
        "slug": 'reverse-bits',
        "difficulty": 'EASY',
        "topic": 'ARRAY',
        "category": 'Bit Manipulation',
        "description": '# Reverse Bits\n\n## Statement\nA classic easy problem in the "Bit Manipulation" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Missing Number',
        "slug": 'missing-number',
        "difficulty": 'EASY',
        "topic": 'ARRAY',
        "category": 'Bit Manipulation',
        "description": '# Missing Number\n\n## Statement\nA classic easy problem in the "Bit Manipulation" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Sum of Two Integers',
        "slug": 'sum-of-two-integers',
        "difficulty": 'MEDIUM',
        "topic": 'ARRAY',
        "category": 'Bit Manipulation',
        "description": '# Sum of Two Integers\n\n## Statement\nA classic medium problem in the "Bit Manipulation" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
    {
        "title": 'Reverse Integer',
        "slug": 'reverse-integer',
        "difficulty": 'MEDIUM',
        "topic": 'ARRAY',
        "category": 'Bit Manipulation',
        "description": '# Reverse Integer\n\n## Statement\nA classic medium problem in the "Bit Manipulation" category of the NeetCode 150 interview prep list. Read the problem statement and constraints, identify the underlying algorithmic pattern, then implement an efficient solution.\n\n## Note\nThis problem is part of the curated study catalog and is queued for full authoring (example inputs, constraints, and runnable starter code).',
    },
]

# Enrich catalog-only entries with fully-authored content (description, starter
# code, test cases) from the authoring manifest. Entries without authored content
# remain catalog placeholders. Already-authored problems are NOT included in the
# manifest, so their DB content is never clobbered.
from app.seeds.neetcode_authoring import NEETCODE_AUTHORING as _AUTHORING

for _entry in NEETCODE_150:
    _auth = _AUTHORING.get(_entry["slug"])
    if _auth:
        _entry.update(_auth)
        # The authoring manifest uses TestCase models while the rest of the
        # pipeline (verify_seeds.py, check_starters.py) expects plain dicts.
        # Normalise here so every PROBLEMS entry has the same shape.
        _entry["test_cases"] = [
            _tc if isinstance(_tc, dict) else _tc.model_dump()
            for _tc in _entry.get("test_cases", [])
        ]

del _AUTHORING, _entry, _auth

